import React, { useEffect, useState } from 'react';
import { X, Sparkles, RefreshCw, AlertCircle } from 'lucide-react';
import './SmartBriefingModal.css';
import api from '../../services/api';

interface SmartBriefingModalProps {
  onClose: () => void;
}

interface BriefingData {
  title: string;
  content: string;
  keyPoints: string[];
}

const SmartBriefingModal: React.FC<SmartBriefingModalProps> = ({ onClose }) => {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState<BriefingData | null>(null);
  const [error, setError] = useState<string | null>(null);

  const fetchBriefing = async () => {
    setLoading(true);
    setError(null);
    try {
      // Assuming the endpoint is /articles/smart-briefing
      const response = await api.get('/articles/smart-briefing');
      console.log('Briefing API Response:', response);

      // Handle response structure: { status: 'success', data: { title, content, keyPoints } }
      if (response.data && response.data.status === 'success') {
        setData(response.data.data);
      } else {
        throw new Error('Invalid response format');
      }
    } catch (err) {
      console.error('Failed to load smart briefing:', err);
      setError('Unable to generate your briefing at this moment. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBriefing();
  }, []);

  return (
    <div className="smart-briefing-overlay" onClick={onClose}>
      <div className="smart-briefing-modal" onClick={(e) => e.stopPropagation()}>
        <div className="smart-briefing-header">
          <div className="header-title">
            <Sparkles className="sparkle-icon" size={20} />
            <h2>Smart Briefing</h2>
          </div>
          <button className="close-button" onClick={onClose}>
            <X size={24} />
          </button>
        </div>

        <div className="smart-briefing-content">
          {loading ? (
            <div className="briefing-loading">
              <div className="skeleton-title"></div>
              <div className="skeleton-line"></div>
              <div className="skeleton-line"></div>
              <div className="skeleton-line short"></div>
              <div className="skeleton-list">
                 <div className="skeleton-bullet"></div>
                 <div className="skeleton-bullet"></div>
                 <div className="skeleton-bullet"></div>
              </div>
            </div>
          ) : error ? (
            <div className="briefing-error">
              <AlertCircle size={48} className="error-icon" />
              <p>{error}</p>
              <button className="retry-button" onClick={fetchBriefing}>
                <RefreshCw size={16} /> Retry
              </button>
            </div>
          ) : data ? (
            <div className="briefing-body">
              <h3 className="briefing-headline">{data.title}</h3>
              <p className="briefing-summary">{data.content}</p>
              
              {data.keyPoints && data.keyPoints.length > 0 && (
                <div className="briefing-points">
                  <h4>Key Takeaways</h4>
                  <ul>
                    {data.keyPoints.map((point, index) => (
                      <li key={index}>{point}</li>
                    ))}
                  </ul>
                </div>
              )}
              
              <div className="briefing-footer">
                <p>Generated by Narrative AI based on your recent feed.</p>
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </div>
  );
};

export default SmartBriefingModal;
