import React, { useEffect, useState, useRef } from 'react';
import { createPortal } from 'react-dom';
import { 
  Close as CloseIcon, 
  AutoAwesome as SparklesIcon, 
  Refresh as RefreshIcon, 
  ErrorOutline as AlertIcon 
} from '@mui/icons-material';
import './SmartBriefingModal.css';
import api from '../../services/api';
import { IArticle } from '../../types';

interface BriefingData {
  title: string;
  content: string;
  keyPoints: string[];
}

interface SmartBriefingModalProps {
  onClose: () => void;
  article?: IArticle;
  onCompare?: (article: IArticle) => void;
  showTooltip?: (text: string, e: React.MouseEvent) => void;
}

const SmartBriefingModal: React.FC<SmartBriefingModalProps> = ({ 
  onClose,
  article 
}) => {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState<BriefingData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const mounted = useRef(true);

  // cleanup on unmount
  useEffect(() => {
    return () => {
      mounted.current = false;
    };
  }, []);

  const fetchBriefing = async () => {
    setLoading(true);
    setError(null);
    
    // Timeout to prevent hanging
    const timeoutPromise = new Promise((_, reject) => 
      setTimeout(() => reject(new Error('Request timed out')), 15000)
    );

    try {
      // Race between the API call and the timeout
      const response: any = await Promise.race([
        api.get('/articles/smart-briefing'),
        timeoutPromise
      ]);
      
      if (!mounted.current) return;

      console.log('Briefing API Response:', response);

      if (response.data && response.data.status === 'success') {
        setData(response.data.data);
      } else {
        throw new Error('Invalid response format');
      }
    } catch (err: any) {
      if (!mounted.current) return;
      console.error('Failed to load smart briefing:', err);
      
      if (err.message === 'Request timed out') {
        setError('The briefing is taking longer than usual. Please try again.');
      } else {
        setError('Unable to generate your briefing at this moment.');
      }
    } finally {
      if (mounted.current) {
        setLoading(false);
      }
    }
  };

  useEffect(() => {
    fetchBriefing();
  }, []);

  // We use a Portal to render this component at the document.body level.
  // This breaks it out of any stacking contexts or overflow:hidden containers.
  return createPortal(
    <div className="smart-briefing-overlay" onClick={onClose}>
      <div 
        className="smart-briefing-modal" 
        onClick={(e) => e.stopPropagation()}
        // Inline styles to guarantee visibility against any global CSS conflicts
        style={{ 
          opacity: 1, 
          visibility: 'visible', 
          display: 'flex',
          transform: 'none' 
        }}
      >
        
        {/* Header - Always visible */}
        <div className="smart-briefing-header">
          <div className="header-title">
            <SparklesIcon sx={{ color: '#8b5cf6', fontSize: 24 }} />
            <h2>{article ? 'Smart Analysis' : 'Smart Briefing'}</h2>
          </div>
          <button className="close-button" onClick={onClose} aria-label="Close">
            <CloseIcon sx={{ fontSize: 24 }} />
          </button>
        </div>

        {/* Content Body */}
        <div className="smart-briefing-content">
          {loading ? (
            <div className="briefing-loading">
              <p className="loading-text">Analyzing current events...</p>
              <div className="skeleton-title"></div>
              <div className="skeleton-line"></div>
              <div className="skeleton-line"></div>
              <div className="skeleton-line short"></div>
            </div>
          ) : error ? (
            <div className="briefing-error">
              <AlertIcon sx={{ fontSize: 48, color: '#ef4444', marginBottom: '1rem' }} />
              <p>{error}</p>
              <button className="retry-button" onClick={fetchBriefing}>
                <RefreshIcon sx={{ fontSize: 16, marginRight: '8px' }} /> Retry
              </button>
            </div>
          ) : data ? (
            <div className="briefing-body">
              <h3 className="briefing-headline">
                {article ? `Context: ${article.headline}` : data.title}
              </h3>
              
              <p className="briefing-summary">{data.content}</p>
              
              {data.keyPoints && data.keyPoints.length > 0 && (
                <div className="briefing-points">
                  <h4>Key Takeaways</h4>
                  <ul>
                    {data.keyPoints.map((point, index) => (
                      <li key={index}>{point}</li>
                    ))}
                  </ul>
                </div>
              )}
              
              <div className="briefing-footer">
                <p>Generated by Narrative AI based on live reporting.</p>
              </div>
            </div>
          ) : (
             <div className="briefing-error">
                <p>No briefing data available.</p>
                <button className="retry-button" onClick={fetchBriefing}>
                  <RefreshIcon sx={{ fontSize: 16, marginRight: '8px' }} /> Retry
                </button>
             </div>
          )}
        </div>
      </div>
    </div>,
    document.body // Target container
  );
};

export default SmartBriefingModal;
