// src/pages/admin/Narratives.tsx
import React, { useState, useEffect } from 'react';
import { adminService } from '../../services/adminService';
import { INarrative } from '../../types';
import PageLoader from '../../components/PageLoader';
import { AdminPageHeader } from '../../components/admin/AdminPageHeader';
import { AdminTable } from '../../components/admin/AdminTable';
import './Admin.css';

const Narratives: React.FC = () => {
  const [loading, setLoading] = useState(true);
  const [narratives, setNarratives] = useState<INarrative[]>([]);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  // Edit State
  const [isEditing, setIsEditing] = useState(false);
  const [editData, setEditData] = useState<Partial<INarrative> | null>(null);

  const fetchNarratives = async () => {
    setLoading(true);
    try {
      const res = await adminService.getAllNarratives(page);
      setNarratives(res.data.data.narratives);
      setTotalPages(res.data.pages);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchNarratives();
  }, [page]);

  const handleEdit = (item: INarrative) => {
    setEditData(JSON.parse(JSON.stringify(item))); // Deep copy
    setIsEditing(true);
  };

  const handleSave = async () => {
    if (!editData || !editData._id) return;
    try {
        await adminService.updateNarrative(editData._id, editData);
        alert('Narrative updated');
        setIsEditing(false);
        fetchNarratives();
    } catch (err) {
        alert('Failed to update narrative');
    }
  };

  // --- Array Editors ---
  const handleConsensusChange = (index: number, val: string) => {
      if(!editData) return;
      const newArr = [...(editData.consensusPoints || [])];
      newArr[index] = val;
      setEditData({...editData, consensusPoints: newArr});
  };

  const addConsensus = () => {
      if(!editData) return;
      setEditData({...editData, consensusPoints: [...(editData.consensusPoints || []), "New Point"]});
  };

  const removeConsensus = (index: number) => {
      if(!editData) return;
      const newArr = [...(editData.consensusPoints || [])];
      newArr.splice(index, 1);
      setEditData({...editData, consensusPoints: newArr});
  };

  const columns = [
    { header: 'Cluster ID', accessor: 'clusterId' },
    { header: 'Master Headline', accessor: 'masterHeadline' },
    { header: 'Sources', accessor: 'sourceCount' },
    { header: 'Updated', accessor: (row: INarrative) => new Date(row.lastUpdated).toLocaleDateString() },
    { 
        header: 'Actions', 
        accessor: (row: INarrative) => (
            <button className="btn btn-outline btn-sm" onClick={() => handleEdit(row)}>Edit</button>
        )
    }
  ];

  if (loading && !narratives.length) return <PageLoader />;

  return (
    <div>
      <AdminPageHeader title="Narrative Clusters" description="Manage the meta-stories generated by AI." />
      
      <AdminTable 
         data={narratives}
         columns={columns}
         currentPage={page}
         totalPages={totalPages}
         onPageChange={setPage}
      />

      {/* EDIT MODAL */}
      {isEditing && editData && (
         <div className="admin-modal-overlay">
            <div className="admin-modal" style={{maxWidth:'800px'}}>
               <h2>Edit Narrative</h2>
               
               <div className="admin-form-group">
                  <label>Master Headline</label>
                  <input 
                    value={editData.masterHeadline} 
                    onChange={e => setEditData({...editData, masterHeadline: e.target.value})}
                    className="form-input"
                  />
               </div>

               <div className="admin-form-group">
                  <label>Executive Summary</label>
                  <textarea 
                    value={editData.executiveSummary} 
                    onChange={e => setEditData({...editData, executiveSummary: e.target.value})}
                    className="form-textarea"
                    style={{height:'100px'}}
                  />
               </div>

               <div style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:'16px'}}>
                  <div className="admin-form-group">
                     <label>Category</label>
                     <input value={editData.category} onChange={e => setEditData({...editData, category: e.target.value})} className="form-input" />
                  </div>
                  <div className="admin-form-group">
                     <label>Country</label>
                     <input value={editData.country} onChange={e => setEditData({...editData, country: e.target.value})} className="form-input" />
                  </div>
               </div>

               {/* Consensus Points Editor */}
               <div style={{marginTop:'20px'}}>
                   <div className="flex-between">
                      <label style={{fontWeight:'bold'}}>Consensus Points</label>
                      <button onClick={addConsensus} className="btn btn-sm btn-outline">+ Add</button>
                   </div>
                   {editData.consensusPoints?.map((point, idx) => (
                       <div key={idx} style={{display:'flex', gap:'8px', marginTop:'8px'}}>
                           <input 
                             value={point} 
                             onChange={e => handleConsensusChange(idx, e.target.value)}
                             className="form-input"
                           />
                           <button onClick={() => removeConsensus(idx)} className="text-red" style={{border:'none', background:'none', cursor:'pointer'}}>X</button>
                       </div>
                   ))}
               </div>

               {/* Divergence Points (Read Only for now due to complexity, or simple JSON edit) */}
               <div style={{marginTop:'20px'}}>
                   <label style={{fontWeight:'bold'}}>Divergence Points (JSON)</label>
                   <p style={{fontSize:'0.8rem', color:'#666'}}>Advanced: Edit the JSON structure for disagreements.</p>
                   <textarea 
                      className="form-textarea font-mono"
                      value={JSON.stringify(editData.divergencePoints, null, 2)}
                      onChange={e => {
                          try {
                              const parsed = JSON.parse(e.target.value);
                              setEditData({...editData, divergencePoints: parsed});
                          } catch (err) {
                              // Allow typing invalid JSON temporarily
                          }
                      }}
                      style={{height:'200px', fontSize:'12px'}}
                   />
               </div>

               <div className="flex-end" style={{marginTop:'24px'}}>
                  <button className="btn btn-outline" onClick={() => setIsEditing(false)}>Cancel</button>
                  <button className="btn btn-primary" onClick={handleSave}>Save Changes</button>
               </div>
            </div>
         </div>
      )}
    </div>
  );
};

export default Narratives;
